# Generated by Django 5.1.1 on 2024-09-10 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifyrecord_remove_user_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='email',
            field=models.EmailField(default='894618229@qq.com', max_length=50, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 16, 49, 55, 164343), verbose_name='发送时间'),
        ),
    ]
