# Generated by Django 5.1.1 on 2024-09-11 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_diagnosis_user_type_user_workschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 19, 51, 3, 98385), verbose_name='发送时间'),
        ),
    ]
