# Generated by Django 5.1.1 on 2024-09-11 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_emailverifyrecord_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 20, 16, 46, 34890), verbose_name='发送时间'),
        ),
    ]
