# Generated by Django 5.1.1 on 2024-09-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='药品名称'),
        ),
    ]
